ok

diff --git a/server/aesdsocket-start-stop b/server/aesdsocket-start-stop
--- a/server/aesdsocket-start-stop
+++ b/server/aesdsocket-start-stop
@@ -1,15 +1,36 @@
 #!/bin/sh
 
+# Description: start/stop init script for the aesd socket server application assignment
+
+do_start() {
+    AESDSOCKET_ARGS="$AESDSOCKET_ARGS -d"
+    printf "Starting aesdsocket as daemon..."
+    umask 077
+    
+    start-stop-daemon -S -q -p /var/run/aesdsocket.pid --exec /usr/bin/aesdsocket -- $AESDSOCKET_ARGS
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+}
+
+do_stop() {
+    printf "Stopping aesdsocket..."
+    start-stop-daemon -K -q -p /var/run/aesdsocket.pid -s SIGTERM
+    [ $? = 0 ] && echo "OK" || echo "FAIL"
+}
+
 case "$1" in
-  start)
-    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
-    ;;
-  stop)
-    start-stop-daemon -K -n aesdsocket
-    ;;
-  *)
-    echo "Usage: $0 { start | stop }"
-    exit 1
+    start)
+        do_start
+        ;;
+    stop)
+        do_stop
+        ;;
+    restart)
+        do_stop
+        do_start
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|restart}"
 esac
 
 exit 0
+        
